### ISSUE TITLE
Signal Game: conflicting option string

### ISSUE THREAD

**Issue by feipenghe** [facebookresearch/EGG#34]
Hi, I am totally new to this project and I encountered an issue when I try to run signal_game.train. The issue remains even after I specify vocabulary size. Can anybody give me some instructions?

`(env) pengfeihe@D-10-18-202-82 EGG-master % python -m egg.zoo.signal_game.train
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/pengfeihe/Library/Mobile Documents/com~apple~CloudDocs/Programming Language/Python/Emergent Communication/EGG-master/egg/zoo/signal_game/train.py", line 85, in <module>
    opts = parse_arguments()
  File "/Users/pengfeihe/Library/Mobile Documents/com~apple~CloudDocs/Programming Language/Python/Emergent Communication/EGG-master/egg/zoo/signal_game/train.py", line 41, in parse_arguments
    opt = core.init(parser)
  File "/Users/pengfeihe/Library/Mobile Documents/com~apple~CloudDocs/Programming Language/Python/Emergent Communication/EGG-master/egg/core/util.py", line 96, in init
    arg_parser = _populate_cl_params(arg_parser)
  File "/Users/pengfeihe/Library/Mobile Documents/com~apple~CloudDocs/Programming Language/Python/Emergent Communication/EGG-master/egg/core/util.py", line 55, in _populate_cl_params
    help='Number of symbols (terms) in the vocabulary (default: 10)')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1367, in add_argument
    return self._add_action(action)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1730, in _add_action
    self._optionals._add_action(action)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1571, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1381, in _add_action
    self._check_conflict(action)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1520, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1529, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --vocab_size: conflicting option string: --vocab_size`

**Comment by eugene-kharitonov** [comment]
Hello @feipenghe , thanks for reporting the issue. I believe it should be fixed now.

But note that this game does not come with a dataset, so it might be not the best game for getting started...
