### ISSUE TITLE
Trouble loading data while running signal game

### ISSUE THREAD

**Issue by feipenghe** [facebookresearch/EGG#41]
Hi,
I ran into a problem of loading the h5 dataset. Previously I tried and it worked. But after I "pip install -e . ", it has a problem as below. I am NOT sure if that's the reason for it, just FYI.

<HDF5 file "ours_images_single_sm0.h5" (mode r)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/usr/Documents//Emergent Communication/EGG-master/egg/zoo/signal_game/train.py", line 87, in <module>
    dataset = ImageNetFeat(root=data_folder)
  File "/Users/usr/Documents/Emergent Communication/EGG-master/egg/zoo/signal_game/features.py", line 120, in __init__
    labels = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\x00'.

**Comment by eugene-kharitonov** [comment]
Thanks for pointing!
