### ISSUE TITLE
Is Signaling Game Working?

### ISSUE THREAD

**Issue by Gromite** [facebookresearch/EGG#97]
Hi, I was trying to make Signaling Game work but encountered a lot of problems trying to do so. I have the original data. Is it working? If it does, which versions of Python Torch, or other dependencies should I use?

**Comment by eugene-kharitonov** [comment]
Hello @Gromite ,
It shouldn't have any dependencies apart from EGG itself. Once you installed it, it should work.

Can you share some details on what's not working? I'll have a look.

**Comment by Gromite** [comment]
Thanks for your quick answer, I am new to Language Games and wanted to start with EGG. I tried to explaine the errors I encountered and steps I took. 

I have Python 3.7.8, PyTorch 1.1.0 (as recommended) and CUDA 10 installed. I have an environment for EGG. I downloaded EGG via https.  Then I tried to start train.py with 
`python -m egg.zoo.signal_game.train --root=/private/home/kharitonov/work/egg/data/concepts/`
with appropriate data root (I got it from the author of original paper as you mentioned.)
Then I had to pip install module called 'h5py'. 
Then the program gave a value error: 
`Traceback (most recent call last):
  File "C:\Users\usr\anaconda3\envs\egg37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usr\anaconda3\envs\egg37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\zoo\signal_game\train.py", line 106, in <module>
    trainer.train(n_epochs=opts.n_epochs)
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\core\trainers.py", line 160, in train
    train_loss, train_interaction = self.train_epoch()
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\core\trainers.py", line 132, in train_epoch
    for batch in self.train_data:
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\zoo\signal_game\features.py", line 89, in __iter__
    seed = np.random.randint(0, 2 ** 32)
  File "mtrand.pyx", line 744, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1343, in numpy.random._bounded_integers._rand_int32
ValueError: high is out of bounds for int32`
I kind of fixed the error by decreasing the number 2**32 to 2**31 in the _Interaction_ python file (C:\Users\usr\anaconda3\envs\egg37\Lib\site-packages\egg\zoo\signal_game\features.py).  
Then I got the following error `Traceback (most recent call last):
  File "C:\Users\usr\anaconda3\envs\egg37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usr\anaconda3\envs\egg37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\zoo\signal_game\train.py", line 106, in <module>
    trainer.train(n_epochs=opts.n_epochs)
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\core\trainers.py", line 160, in train
    train_loss, train_interaction = self.train_epoch()
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\core\trainers.py", line 149, in train_epoch
    full_interaction = Interaction.from_iterable(interactions)
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\core\interaction.py", line 111, in from_iterable
    aux[k] = _check_cat([x.aux[k] for x in interactions])
  File "C:\Users\usr\anaconda3\envs\egg37\lib\site-packages\egg\core\interaction.py", line 103, in _check_cat
    return torch.cat(lst, dim=0)
TypeError: expected Tensor as element 0 in argument 0, but got float`

I am not able to solve this issue, do you have any idea how to solve it or did I do anything wrong?

**Comment by eugene-kharitonov** [comment]
@Gromite Hello, I think it works for me now. Can you verify? Thanks!

**Comment by Gromite** [comment]
Yes, it is fixed thank you!
